import 'package:flutter/material.dart';
import 'one_line_models.dart';

class OneLineShapes {
  static final List<OneLineLevel> levels = [
    // Level 1: Triangle (simple)
    OneLineLevel(
      levelNumber: 1,
      shape: OneLineShape(
        name: 'Triangle',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.5, 0.15)),
          OneLineVertex(id: 1, position: const Offset(0.15, 0.85)),
          OneLineVertex(id: 2, position: const Offset(0.85, 0.85)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 0),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [],
        suggestedStartVertex: 0,
      ),
      hint: 'Start at the top and go around.',
      parTime: 8,
    ),
    // Level 2: Square
    OneLineLevel(
      levelNumber: 2,
      shape: OneLineShape(
        name: 'Square',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.2, 0.2)),
          OneLineVertex(id: 1, position: const Offset(0.8, 0.2)),
          OneLineVertex(id: 2, position: const Offset(0.8, 0.8)),
          OneLineVertex(id: 3, position: const Offset(0.2, 0.8)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 3),
          OneLineEdge(id: 3, startVertexId: 3, endVertexId: 0),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [],
        suggestedStartVertex: 0,
      ),
      hint: 'Trace the perimeter clockwise.',
      parTime: 10,
    ),
    // Level 3: Triangle with center point (star-like)
    OneLineLevel(
      levelNumber: 3,
      shape: OneLineShape(
        name: 'Envelope',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.2, 0.2)),
          OneLineVertex(id: 1, position: const Offset(0.8, 0.2)),
          OneLineVertex(id: 2, position: const Offset(0.8, 0.8)),
          OneLineVertex(id: 3, position: const Offset(0.2, 0.8)),
          OneLineVertex(id: 4, position: const Offset(0.5, 0.5)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 3),
          OneLineEdge(id: 3, startVertexId: 3, endVertexId: 0),
          OneLineEdge(id: 4, startVertexId: 0, endVertexId: 4),
          OneLineEdge(id: 5, startVertexId: 1, endVertexId: 4),
          OneLineEdge(id: 6, startVertexId: 2, endVertexId: 4),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [0, 1, 2],
        suggestedStartVertex: 0,
      ),
      hint: 'Start at a corner with 3 connections.',
      parTime: 14,
    ),
    // Level 4: Arrow
    OneLineLevel(
      levelNumber: 4,
      shape: OneLineShape(
        name: 'Arrow',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.5, 0.1)),
          OneLineVertex(id: 1, position: const Offset(0.85, 0.45)),
          OneLineVertex(id: 2, position: const Offset(0.65, 0.45)),
          OneLineVertex(id: 3, position: const Offset(0.65, 0.9)),
          OneLineVertex(id: 4, position: const Offset(0.35, 0.9)),
          OneLineVertex(id: 5, position: const Offset(0.35, 0.45)),
          OneLineVertex(id: 6, position: const Offset(0.15, 0.45)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 3),
          OneLineEdge(id: 3, startVertexId: 3, endVertexId: 4),
          OneLineEdge(id: 4, startVertexId: 4, endVertexId: 5),
          OneLineEdge(id: 5, startVertexId: 5, endVertexId: 6),
          OneLineEdge(id: 6, startVertexId: 6, endVertexId: 0),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [],
        suggestedStartVertex: 0,
      ),
      hint: 'Trace the arrow outline.',
      parTime: 14,
    ),
    // Level 5: House
    OneLineLevel(
      levelNumber: 5,
      shape: OneLineShape(
        name: 'House',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.5, 0.1)),
          OneLineVertex(id: 1, position: const Offset(0.85, 0.4)),
          OneLineVertex(id: 2, position: const Offset(0.85, 0.9)),
          OneLineVertex(id: 3, position: const Offset(0.15, 0.9)),
          OneLineVertex(id: 4, position: const Offset(0.15, 0.4)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 3),
          OneLineEdge(id: 3, startVertexId: 3, endVertexId: 4),
          OneLineEdge(id: 4, startVertexId: 4, endVertexId: 0),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [],
        suggestedStartVertex: 0,
      ),
      hint: 'Start at the roof peak.',
      parTime: 12,
    ),
    // Level 6: Pentagon
    OneLineLevel(
      levelNumber: 6,
      shape: OneLineShape(
        name: 'Pentagon',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.5, 0.1)),
          OneLineVertex(id: 1, position: const Offset(0.9, 0.4)),
          OneLineVertex(id: 2, position: const Offset(0.75, 0.85)),
          OneLineVertex(id: 3, position: const Offset(0.25, 0.85)),
          OneLineVertex(id: 4, position: const Offset(0.1, 0.4)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 3),
          OneLineEdge(id: 3, startVertexId: 3, endVertexId: 4),
          OneLineEdge(id: 4, startVertexId: 4, endVertexId: 0),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [],
        suggestedStartVertex: 0,
      ),
      hint: 'Trace the pentagon perimeter.',
      parTime: 12,
    ),
    // Level 7: Star (5-point)
    OneLineLevel(
      levelNumber: 7,
      shape: OneLineShape(
        name: 'Star',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.5, 0.08)),
          OneLineVertex(id: 1, position: const Offset(0.62, 0.38)),
          OneLineVertex(id: 2, position: const Offset(0.95, 0.38)),
          OneLineVertex(id: 3, position: const Offset(0.69, 0.58)),
          OneLineVertex(id: 4, position: const Offset(0.79, 0.92)),
          OneLineVertex(id: 5, position: const Offset(0.5, 0.72)),
          OneLineVertex(id: 6, position: const Offset(0.21, 0.92)),
          OneLineVertex(id: 7, position: const Offset(0.31, 0.58)),
          OneLineVertex(id: 8, position: const Offset(0.05, 0.38)),
          OneLineVertex(id: 9, position: const Offset(0.38, 0.38)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 3),
          OneLineEdge(id: 1, startVertexId: 3, endVertexId: 6),
          OneLineEdge(id: 2, startVertexId: 6, endVertexId: 9),
          OneLineEdge(id: 3, startVertexId: 9, endVertexId: 2),
          OneLineEdge(id: 4, startVertexId: 2, endVertexId: 5),
          OneLineEdge(id: 5, startVertexId: 5, endVertexId: 8),
          OneLineEdge(id: 6, startVertexId: 8, endVertexId: 1),
          OneLineEdge(id: 7, startVertexId: 1, endVertexId: 4),
          OneLineEdge(id: 8, startVertexId: 4, endVertexId: 7),
          OneLineEdge(id: 9, startVertexId: 7, endVertexId: 0),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [],
        suggestedStartVertex: 0,
      ),
      hint: 'Draw the star by connecting every other point.',
      parTime: 18,
    ),
    // Level 8: Hexagon
    OneLineLevel(
      levelNumber: 8,
      shape: OneLineShape(
        name: 'Hexagon',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.5, 0.1)),
          OneLineVertex(id: 1, position: const Offset(0.87, 0.3)),
          OneLineVertex(id: 2, position: const Offset(0.87, 0.7)),
          OneLineVertex(id: 3, position: const Offset(0.5, 0.9)),
          OneLineVertex(id: 4, position: const Offset(0.13, 0.7)),
          OneLineVertex(id: 5, position: const Offset(0.13, 0.3)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 3),
          OneLineEdge(id: 3, startVertexId: 3, endVertexId: 4),
          OneLineEdge(id: 4, startVertexId: 4, endVertexId: 5),
          OneLineEdge(id: 5, startVertexId: 5, endVertexId: 0),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [],
        suggestedStartVertex: 0,
      ),
      hint: 'Trace the hexagon perimeter.',
      parTime: 14,
    ),
    // Level 9: Cross / Plus
    OneLineLevel(
      levelNumber: 9,
      shape: OneLineShape(
        name: 'Cross',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.35, 0.1)),
          OneLineVertex(id: 1, position: const Offset(0.65, 0.1)),
          OneLineVertex(id: 2, position: const Offset(0.65, 0.35)),
          OneLineVertex(id: 3, position: const Offset(0.9, 0.35)),
          OneLineVertex(id: 4, position: const Offset(0.9, 0.65)),
          OneLineVertex(id: 5, position: const Offset(0.65, 0.65)),
          OneLineVertex(id: 6, position: const Offset(0.65, 0.9)),
          OneLineVertex(id: 7, position: const Offset(0.35, 0.9)),
          OneLineVertex(id: 8, position: const Offset(0.35, 0.65)),
          OneLineVertex(id: 9, position: const Offset(0.1, 0.65)),
          OneLineVertex(id: 10, position: const Offset(0.1, 0.35)),
          OneLineVertex(id: 11, position: const Offset(0.35, 0.35)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 3),
          OneLineEdge(id: 3, startVertexId: 3, endVertexId: 4),
          OneLineEdge(id: 4, startVertexId: 4, endVertexId: 5),
          OneLineEdge(id: 5, startVertexId: 5, endVertexId: 6),
          OneLineEdge(id: 6, startVertexId: 6, endVertexId: 7),
          OneLineEdge(id: 7, startVertexId: 7, endVertexId: 8),
          OneLineEdge(id: 8, startVertexId: 8, endVertexId: 9),
          OneLineEdge(id: 9, startVertexId: 9, endVertexId: 10),
          OneLineEdge(id: 10, startVertexId: 10, endVertexId: 11),
          OneLineEdge(id: 11, startVertexId: 11, endVertexId: 0),
        ],
        hasEulerPath: true,
        oddDegreeVertices: [],
        suggestedStartVertex: 0,
      ),
      hint: 'Trace the cross outline.',
      parTime: 20,
    ),
    // Level 10: Cube (3D projection)
    OneLineLevel(
      levelNumber: 10,
      shape: OneLineShape(
        name: 'Cube',
        vertices: [
          OneLineVertex(id: 0, position: const Offset(0.25, 0.25)),
          OneLineVertex(id: 1, position: const Offset(0.65, 0.25)),
          OneLineVertex(id: 2, position: const Offset(0.65, 0.65)),
          OneLineVertex(id: 3, position: const Offset(0.25, 0.65)),
          OneLineVertex(id: 4, position: const Offset(0.4, 0.1)),
          OneLineVertex(id: 5, position: const Offset(0.8, 0.1)),
          OneLineVertex(id: 6, position: const Offset(0.8, 0.5)),
          OneLineVertex(id: 7, position: const Offset(0.4, 0.5)),
        ],
        edges: [
          OneLineEdge(id: 0, startVertexId: 0, endVertexId: 1),
          OneLineEdge(id: 1, startVertexId: 1, endVertexId: 2),
          OneLineEdge(id: 2, startVertexId: 2, endVertexId: 3),
          OneLineEdge(id: 3, startVertexId: 3, endVertexId: 0),
          OneLineEdge(id: 4, startVertexId: 4, endVertexId: 5),
          OneLineEdge(id: 5, startVertexId: 5, endVertexId: 6),
          OneLineEdge(id: 6, startVertexId: 6, endVertexId: 7),
          OneLineEdge(id: 7, startVertexId: 7, endVertexId: 4),
          OneLineEdge(id: 8, startVertexId: 0, endVertexId: 4),
          OneLineEdge(id: 9, startVertexId: 1, endVertexId: 5),
          OneLineEdge(id: 10, startVertexId: 2, endVertexId: 6),
          OneLineEdge(id: 11, startVertexId: 3, endVertexId: 7),
        ],
        hasEulerPath: false,
        oddDegreeVertices: [0, 1, 2, 3, 4, 5, 6, 7],
        suggestedStartVertex: 0,
      ),
      hint: 'This shape has no single-stroke solution. Try to cover as many edges as possible!',
      parTime: 25,
    ),
  ];
}
